### ISSUE TITLE
Discussion: Dask API

### ISSUE THREAD

**Issue by seibert** [metagraph-dev/metagraph#114]
# Goals
The Dask API for Metagraph needs to:

* Create lazy versions of dispatchable types and wrappers (like Graph, EdgeList, etc) that behave like other Dask data types
* Expose lazy wrappers around algorithms that can take either lazy types or regular types as inputs and return lazy types as outputs.
* Expose lazy wrappers around translations as well

Unlike other dask-aware data types, we are not looking to make Graphs, etc partitioned, as we are deferring any choices about parallel data layouts to the backend which likely needs to communicate in a lower overhead, more tightly coupled way (like MPI).  However, we also will want to enable translators (and maybe some algorithms) that take in Dask partitioned data structures (like dask.dataframe and dask.array) as inputs and do the conversion in a parallel fashion if possible.  Example here would be taking a Dask dataframe edge list loaded from many worker nodes and turning it into a Graph in a backend that has some kind of distributed shared memory.  We don't need to address this use case immediately, but we should keep it in mind.

# Example Syntax

This is a rough sketch of how this could look to start discussion:

``` python
import dask.dataframe as dd
import metagraph.dask as dg  # for "dask graph"

passenger_flow_df = dd.read_csv("airline.csv")
# do some data prep here

passenger_flow_edge_map = dg.EdgeMap.PandasEdgeMap(passenger_flow_df,
                                                           'ORIGIN_CITY_MARKET_ID',
                                                           'DEST_CITY_MARKET_ID',
                                                           'INVERSE_PASSENGER_COUNT',
                                                           is_directed=True)

passenger_flow_graph = dg.util.graph.build(passenger_flow_edge_map)
betweenness_centrality = dg.centrality.betweenness(passenger_flow_graph, normalize=False)

number_of_best_scores = 15
best_betweenness_centrality_node_vector = dg.util.nodemap.sort(betweenness_centrality, ascending=False, limit=number_of_best_scores)
best_betweenness_centrality_node_set = dg.util.nodeset.from_vector(best_betweenness_centrality_node_vector)
best_betweenness_centrality_node_to_score_map = dg.util.nodemap.select(betweenness_centrality, best_betweenness_centrality_node_set)
best_betweenness_centrality_node_to_score_map

best_betweenness_centrality_node_to_score_map = dg.translate(best_betweenness_centrality_node_to_score_map, dg.NodeMap.PythonNodeMap)

print(best_betweenness_centrality_node_to_score_map.compute().value)
```

Ideally, plugin authors would write no extra code to enable the above.  If a translator or algorithm returns a Dask task graph rather than a bare object, the system should not attempt to wrap the DAG in another Dask object, but just pass it through unchanged.  This will allow concrete algorithms and translators that take Dask inputs to return Dask outputs that respect the partitioning of the input.

**Comment by jim22k** [comment]
`dg` is acting as a lazy resolver. We need one of the following:
- Each resolver can spawn a lazy resolver with its own internal registry
- The `Resolver` constructor can accept a `lazy=True` flag to behave in a lazy mode
   - The default resolver would need something in the config to specify the desired mode

**Comment by paul-tqh-nguyen** [comment]
If we added a `compute` method to all the eager types, the `compute` method would simply return `self`, it seems that both of these approaches could minimize the user burden as well. 

For the spawn-a-lazy-resolver approach, the user would simply take their "eager" code and add 1 line:
```
resolver = mg.resolver
resolver = resolver.generate_lazy_resolver()
```

For the `lazy=True` approach, the user would change the config file if using the default resolver or change their resolver's initializer. 

I have a slight preference for the `spawn-a-lazy-resolver approach` since it's useful to have access to both a lazy and eager resolver while debugging or working in a notebook, but both approaches sound like a good path forward.
