### ISSUE TITLE
Catch accidental use of concrete type in abstract type signature

### ISSUE THREAD

**Issue by seibert** [metagraph-dev/metagraph#171]
This should not be allowed:
``` python
from metagraph import abstract_algorithm, PluginRegistry
from metagraph.plugins.core.types import Vector
from metagraph.plugins.numpy.types import NumpyVectorType

@abstract_algorithm('testing.scale')
def testing_scale(a: Vector, scale: float)->NumpyVectorType:  # oops, bad return type
    pass

registry = PluginRegistry('test_registry')
registry.register(testing_scale)  # this should raise an error
```

**Comment by seibert** [comment]
Actually, I think it might make more sense for the error to be raised when passing the registry to a Resolver.  The PluginRegistry right now does not do any validation (and the Resolver does), and I would rather not split validation into two places.

**Comment by paul-tqh-nguyen** [comment]
https://github.com/metagraph-dev/metagraph/pull/176 addresses this issue.
